//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lithnet.AccessManager.Server.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lithnet.AccessManager.Server.App_LocalResources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to {computer.MsDsPrincipalName} was denied for {user.MsDsPrincipalName}.
        /// </summary>
        internal static string AuditEmailSubjectFailure {
            get {
                return ResourceManager.GetString("AuditEmailSubjectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to {computer.MsDsPrincipalName} was granted for {user.MsDsPrincipalName}.
        /// </summary>
        internal static string AuditEmailSubjectSuccess {
            get {
                return ResourceManager.GetString("AuditEmailSubjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUDIT: FAILURE          
        ///Username:			{user.MsDsPrincipalName}
        ///Name:				{user.DisplayName}
        ///UPN:				{user.UserPrincipalName}
        ///SID:				{user.Sid}
        ///User DN:				{user.DistinguishedName}
        ///Computer name:			{computer.MsDsPrincipalName}
        ///Computer DN:			{computer.DistinguishedName}
        ///Target ID:			{target.ID}
        ///Reader principal:			{reader.Principal}
        ///Detail:				{message}.
        /// </summary>
        internal static string DefaultAuditFailureText {
            get {
                return ResourceManager.GetString("DefaultAuditFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUDIT: SUCCESS       
        ///Username:			{user.MsDsPrincipalName}
        ///Name:				{user.DisplayName}
        ///UPN:				{user.UserPrincipalName}
        ///SID:				{user.Sid}
        ///User DN:				{user.DistinguishedName}
        ///Computer name:			{computer.MsDsPrincipalName}
        ///Computer DN:			{computer.DistinguishedName}
        ///Target ID:			{target.ID}
        ///Reader principal:			{reader.Principal}.
        /// </summary>
        internal static string DefaultAuditSuccessText {
            get {
                return ResourceManager.GetString("DefaultAuditSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification channel &apos;{0}&apos; failed to process the audit message.
        /// </summary>
        internal static string NotificationChannelError {
            get {
                return ResourceManager.GetString("NotificationChannelError", resourceCulture);
            }
        }
    }
}
