USE [AccessManager]
GO
/****** Object:  Table [dbo].[RateLimitCache]    Script Date: 18/10/2020 11:42:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RateLimitCache](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Created] [datetime2](7) NOT NULL,
	[CacheKey] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_RateLimitCache] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_RateLimitCache] ON [dbo].[RateLimitCache]
(
	[Created] ASC,
	[CacheKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO